# Generated by Django 4.0.4 on 2022-08-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
