# Generated by Django 4.0.4 on 2022-08-22 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_item_category_category_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='typo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
    ]
