# Generated by Django 4.0.4 on 2022-08-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_item_typo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='kind',
        ),
    ]
