# Generated by Django 4.0.4 on 2022-08-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_category_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pic',
            field=models.ImageField(default=1, upload_to='', width_field=50),
            preserve_default=False,
        ),
    ]
