# Generated by Django 4.0.4 on 2022-08-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_item_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pic',
            field=models.ImageField(upload_to='picture', width_field=50),
        ),
    ]
